use serde::Deserialize;
use serde_json::Value;

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LoginRoot {
    pub id: i64,
    #[serde(rename = "first_name")]
    pub first_name: String,
    #[serde(rename = "last_name")]
    pub last_name: String,
    #[serde(rename = "mobile_number")]
    pub mobile_number: String,
    #[serde(rename = "em_address")]
    pub em_address: String,
    #[serde(rename = "profile_image_id")]
    pub profile_image_id: Value,
    #[serde(rename = "fb_user_id")]
    pub fb_user_id: Value,
    #[serde(rename = "date_fb_token_expires")]
    pub date_fb_token_expires: Value,
    #[serde(rename = "twit_user_id")]
    pub twit_user_id: Value,
    #[serde(rename = "in_user_id")]
    pub in_user_id: Value,
    #[serde(rename = "em_is_verified")]
    pub em_is_verified: i64,
    #[serde(rename = "mobile_number_is_verified")]
    pub mobile_number_is_verified: i64,
    #[serde(rename = "is_active")]
    pub is_active: i64,
    #[serde(rename = "referral_code")]
    pub referral_code: String,
    #[serde(rename = "date_app_first_opened")]
    pub date_app_first_opened: Value,
    pub bio: Value,
    #[serde(rename = "is_marketable")]
    pub is_marketable: i64,
    #[serde(rename = "date_of_birth")]
    pub date_of_birth: Value,
    #[serde(rename = "is_concierge")]
    pub is_concierge: i64,
    #[serde(rename = "date_updated")]
    pub date_updated: i64,
    #[serde(rename = "date_created")]
    pub date_created: i64,
    #[serde(rename = "has_set_password")]
    pub has_set_password: i64,
    #[serde(rename = "viewed_gda_welcome")]
    pub viewed_gda_welcome: bool,
    #[serde(rename = "num_bookings")]
    pub num_bookings: i64,
    #[serde(rename = "payment_methods")]
    pub payment_methods: Value,
    #[serde(rename = "alternate_mobile_numbers")]
    pub alternate_mobile_numbers: Value,
    #[serde(rename = "venue_credits")]
    pub venue_credits: Value,
    #[serde(rename = "amex_card_types")]
    pub amex_card_types: Vec<Value>,
    #[serde(rename = "resy_select")]
    pub resy_select: i64,
    #[serde(rename = "is_global_dining_access")]
    pub is_global_dining_access: bool,
    #[serde(rename = "profile_image_url")]
    pub profile_image_url: String,
    #[serde(rename = "payment_method_id")]
    pub payment_method_id: Value,
    #[serde(rename = "payment_provider_id")]
    pub payment_provider_id: Value,
    #[serde(rename = "payment_provider_name")]
    pub payment_provider_name: Value,
    #[serde(rename = "payment_display")]
    pub payment_display: Value,
    #[serde(rename = "is_rga")]
    pub is_rga: bool,
    #[serde(rename = "guest_id")]
    pub guest_id: i64,
    pub token: String,
    #[serde(rename = "legacy_token")]
    pub legacy_token: String,
    #[serde(rename = "refresh_token")]
    pub refresh_token: String,
    pub allergies: Value,
    #[serde(rename = "email_opt_out")]
    pub email_opt_out: Vec<Value>,
    #[serde(rename = "venue_opt_in")]
    pub venue_opt_in: Vec<Value>,
}
